/// Flutter icons MonstersDemoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MonstersDemoIcons
///      fonts:
///       - asset: fonts/MonstersDemo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MonstersDemo {
  MonstersDemo._();

  static const _kFontFam = 'MonstersDemo';
  static const _kFontPkg = null;

  static const IconData goblin_head = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_golem = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ogre = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orc_head = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
