/// Flutter icons ObjectsDemo
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ObjectsDemo
///      fonts:
///       - asset: fonts/ObjectsDemo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ObjectsDemo {
  ObjectsDemo._();

  static const _kFontFam = 'ObjectsDemo';
  static const _kFontPkg = null;

  static const IconData barrel = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brick_wall = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lava = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spiky_pit = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spill = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
